; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4
framework = arduino

board_upload.flash_size = 32MB

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DBOARD_HAS_PSRAM
    -O3
    -Wall
    -Wextra
    -Wno-overlength-strings

lib_deps =
    lovyan03/LovyanGFX
    ESP_I2S
    robtillaart/MCP23S17